#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

echo "Nvim config linked"

echo "Installing needed packages"
packages=(
    software-properties-common
    clangd
    npm
)

sudo apt update && sudo apt upgrade

for package in "${packages[@]}"; do
    echo "Installing $package..."
    sudo apt-get install -y "$package"
done
echo "Installing nvim"
wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
tar xzvf nvim-linux-x86_64.tar.gz
alias nvim='./nvim-linux-x86_64/bin/nvim'
echo "Nvim is installed"

"Installing from pip"
pip install basedpyright


echo "All packages from the setup script have been installed."
