#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

echo "Nvim config linked"

echo "Installing needed packages"
packages=(
    software-properties-common
    clangd
    npm
)

for package in "${packages[@]}"; do
    echo "Installing $package..."
    sudo apt-get install -y "$package"
done
echo "Installing nvim"
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt update
sudo apt install -y neovim
echo "Nvim is installed"

"Installing from pip"
pip install basedpyright


echo "All packages from the setup script have been installed."
